GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEzLCJ1c2VybmFtZSI6Im1hdWwiLCJlbWFpbCI6Im1hdWxhbmFAZ21haWwuY29tIiwiaWF0IjoxNjc0ODg2MjQxLCJleHAiOjE2NzQ4ODYzMDF9.rkrVCYAItgQc7AdYFhwDZMca5Ec3nz70prpkIj5sgLg

###
GET http://localhost:5000/token

###
GET http://localhost:5000/links


###
POST http://localhost:5000/links
Content-Type: application/json

{
    "title": "Beats Studio Buds Review Indonesia (GIVEAWAY‼)",
    "links": "https://youtu.be/pXKHa6Vo-Rs",
    "category": "earphone",
    "description": "Unboxing & Review Beats Studio Buds by Apple.\nTWS MFI (Made For iPhone) keluaran apple ini bisa menjadi opsi selain TWS high-end Apple AirPods Pro, Harga yang lebih murah dengan fitur Active Noise Cancelling & Transparency Mode membuat Beats Studio Buds ini layak untuk dicoba! Simak Review Selengkapnya pada video diatas ya! :)\n\nGIVEAWAY ALERT!!! - 1 Pcs Beats Studio Buds (BRAND NEW IN BOX)\n(Info & Persyaratan akan diumumkan di Instagram @belanjabosscom)\nIkutan Ya! Stay Tuned & Good Luck!\n\nSponsored by:\nBelanjaBoss.com\n\nWebsite: https://www.belanjaboss.com/\nInstagram: https://instagram.com/belanjabosscom?...\nWhatsapp: Bit.ly/bb_wa\n\n---------------------------\nBe Social With Me !\n-------------------------------\nInstagram : @indratechlife\nTwitter : @indratechlife\nBusiness Inquires : contact@itech.life\n\nThank You for watching, Please like and subscribe for more videos.",
    "comment_count": 10621,
    "like": 656402
}

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "username": "lucu",
    "email": "mauul@gmail.com",
    "password": "123456",
    "confPassword": "123456"
}


###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "maulana@gmail.com",
    "password": "123"
}

###
DELETE http://localhost:5000/logout
